### ISSUE TITLE
"Registered rnd Extension"

### ISSUE THREAD

**Issue by subsoap** [selimanac/defold-random#6]
This is showing up in release builds when it should not be

https://github.com/selimanac/defold-random/blob/077b5450be53fd42613917a44c4b4d0c4367236e/pcgrandom/src/pcgrandom.cpp#L257

Change

```printf("Registered %s Extension\n", MODULE_NAME);```

to

```dmLogInfo("Registered %s Extension", MODULE_NAME);```

?

**Comment by selimanac** [comment]
Yep, you are right. Fixed. Please check out the main repo.
