### ISSUE TITLE
Error when bundling for Linux

### ISSUE THREAD

**Issue by subsoap** [selimanac/defold-random#7]
Commenting out the line allows bundling

![Screen Shot 2021-07-23 at 7 22 47 PM](https://user-images.githubusercontent.com/409170/126854891-9b4613ad-387f-415e-a42d-f0d7e312fa74.png)

**Comment by selimanac** [comment]
@subsoap could you please check out the main repo. If It is fine, then I'll release a version.

**Comment by subsoap** [comment]
@selimanac Looks good! Good job!
